//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notify
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactId { get; set; }
        public string AnniversaryDate { get; set; }
        public string CellPhone { get; set; }
        public string City { get; set; }
        public string Company { get; set; }
        public string DateOfBirth { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string IsActive { get; set; }
        public string LastName { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public string State { get; set; }
        public string Street { get; set; }
        public string UserMappingId { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
