//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notify
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactListDetail
    {
        public int ListDetailID { get; set; }
        public Nullable<int> ContactListID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
