//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notify
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public string TemplateName { get; set; }
        public string NotificationMessage { get; set; }
        public string NotificationType { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Status { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
