//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notify
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLog
    {
        public int LogId { get; set; }
        public int ClientId { get; set; }
        public int ContactId { get; set; }
        public int NotificaiontStatus { get; set; }
        public int NotificationId { get; set; }
    }
}
