//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notify
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int ResoureId { get; set; }
        public string AccountNumber { get; set; }
        public string CellPhoneNumber { get; set; }
        public string City { get; set; }
        public int ClientId { get; set; }
        public string EmailAddress { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PrimaryPhoneNumber { get; set; }
        public string ResoureDescription { get; set; }
        public string ResoureName { get; set; }
        public string SecondaryPhoneNumber { get; set; }
        public string State { get; set; }
        public string Street { get; set; }
        public string URL { get; set; }
        public string ZipCode { get; set; }
    }
}
