//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notify
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_NotificationSchedule
    {
        public int NScheduleID { get; set; }
        public string NotificationCampaign { get; set; }
        public Nullable<int> ContactListId { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public Nullable<int> NotificationId { get; set; }
        public Nullable<System.DateTime> CampaignDate { get; set; }
        public string ChanelMode { get; set; }
        public string NotificationMessage { get; set; }
        public string RequestConfirmMsg { get; set; }
        public string RepeatNotificationAllow { get; set; }
        public Nullable<int> MsgNumberOfTime { get; set; }
        public Nullable<System.DateTime> ReapeatDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
